---
immuta:
  url: 'https://immuta.hostname.gov'
  apikey: 'immutaapikey'
  limit: 100 # Rate limit Immuta data source processing
  throttle: 1 # Seconds between batch processing
  tls: # Optional
    ca: '/path/to/immuta-ca.crt'

provider:
  id: 'collibra' # The external catalog name as is set in Immuta
  type: 'collibra' # Options: 'collibra'
  url: 'https://collibra.hostname.gov'
  username: 'username'
  password: 'password'
  limit: 0 # Default is no limit (0), this should not tax Collibra
  throttle: 0 # Seconds between batch processing
  match_mode: 'END' # Options: [START|END|ANYWHERE|EXACT], Default: END
  match_prefix: 'prefix>' # Include all characters, including whitespace,  up to the asset name if applicable
  asset_types: # At least one required
    - '00000000-0000-0000-0000-000000031007' # Table
  tls: # Optional
    ca: '/path/to/collibra-ca.crt'
